version: '3.8'

services:
  prospects-flow-service:
    image: ${CI_REGISTRY_IMAGE}:service-prospects
    container_name: prospects-flow-service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - GOOGLE_PLACE_API_KEY=${GOOGLE_PLACE_API_KEY}
      - ENV=production
      - OLLAMA_URL=${OLLAMA_URL:-http://127.0.0.1:11434/api/generate}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - prospects-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  prospects-network:
    driver: bridge 